### ISSUE TITLE
baseInsert 发生异常，在设置称号时

### ISSUE THREAD

**Issue by AlsakaTeam** [handy-git/PlayerChat#4]
无法设置称号，不知道是bug还是因为插件冲突，如果是bug作者就修一下吧
插件列表：
`[17:11:02 INFO]: Paper Plugins: (1):
[17:11:02 INFO]:  - EconomyShopGUI
[17:11:02 INFO]: Bukkit Plugins: (61):
[17:11:02 INFO]:  - AuthMe, BedrockTechnology, *BedwarsRel, ChestCommands, CMILib, ColoredEnderChests, CoreProtect, CrazyAuctionsPlus, DynaTech, EcoPower
[17:11:02 INFO]:  Essentials, ExoticGarden, ExtraHeads, FKBoom, FlowerPower, FluffyMachines, FoxyMachines, Galactifun, GeneticChickengineering, Geyser-Spigot
[17:11:02 INFO]:  GlobalWarming, GoldenDupes, GSit, GuizhanLibPlugin, InfinityExpansion, LastLoginAPI, LiteSignIn, LuckPerms, MiniBlocks, *MultiWorld
[17:11:02 INFO]:  NoDamageImmunity, ObsidianExpansion, *PAPI-ChestCommands, Parties, PistonMOTD, PlaceholderAPI, PlayerChat, PlayerTitle, PlugManX, ProtocolLib
[17:11:02 INFO]:  *RedstoneClockPreventer, Residence, SetSpawn, *ShiftAndF, SimpleTpa, SkinsRestorer, Skywars, Slimefun, SlimefunLuckyBlocks, SlimefunWarfare
[17:11:02 INFO]:  SlimeTinker, SlimyTreeTaps, SmallSpace, spark, TAB, TranscEndence, UltraSetHome, Vault, ViaBackwards, ViaRewind
[17:11:02 INFO]:  ViaVersion`
管理员指令：`/plt player addTitle Migin_Chan &c&l&m腐竹追着打`
聊天栏输出：命令执行失败
控制台输出：
`baseInsert 发生异常
java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver
        at org.sqlite.jdbc3.JDBC3PreparedStatement.unsupported(JDBC3PreparedStatement.java:448) ~[sqlite-jdbc-3.44.1.0.jar:?]
        at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:361) ~[sqlite-jdbc-3.44.1.0.jar:?]
        at PlayerTitle-4.1.3.jar/com.handy.playertitle.lib.expand.zaxxer.hikari.pool.ProxyStatement.getGeneratedKeys(ProxyStatement.java:229) ~[PlayerTitle-4.1.3.jar:?]
        at PlayerTitle-4.1.3.jar/com.handy.playertitle.lib.expand.zaxxer.hikari.pool.HikariProxyPreparedStatement.getGeneratedKeys(HikariProxyPreparedStatement.java) ~[PlayerTitle-4.1.3.jar:?]
        at PlayerTitle-4.1.3.jar/com.handy.playertitle.lib.DbExecution.XXxXXX(ac:658) ~[PlayerTitle-4.1.3.jar:?]
        at PlayerTitle-4.1.3.jar/com.handy.playertitle.lib.DbExecution.insert(ac:379) ~[PlayerTitle-4.1.3.jar:?]
        at PlayerTitle-4.1.3.jar/com.handy.playertitle.service.TitleListService.add(c:106) ~[PlayerTitle-4.1.3.jar:?]
        at PlayerTitle-4.1.3.jar/com.handy.playertitle.command.admin.PlayerCommand.IiIIiiIiiI(kd:70) ~[PlayerTitle-4.1.3.jar:?]
        at PlayerTitle-4.1.3.jar/com.handy.playertitle.command.admin.PlayerCommand.onCommand(kd:128) ~[PlayerTitle-4.1.3.jar:?]
        at PlayerTitle-4.1.3.jar/com.handy.playertitle.lib.iiiIIIiiiI.XXxXxx(mc:109) ~[PlayerTitle-4.1.3.jar:?]
        at PlayerTitle-4.1.3.jar/com.handy.playertitle.lib.iiiIIIiiiI.IiIIiiIiiI(mc:127) ~[PlayerTitle-4.1.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:91) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaf-1.20.4.jar:git-Leaf-"7563d69"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaf-1.20.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by handy-git** [comment]
什么系统？ 看着像你的SQLite数据库出现了问题
然后这是PlayerTitle的报错，你发错地方了
